name: VoxtralMemos
options:
  bundleIdPrefix: com.meltforce
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.2"
    DEVELOPMENT_TEAM: "R43S29F4G5"

packages:
  VoxtralCore:
    path: VoxtralCore

targets:
  VoxtralMemos:
    type: application
    platform: iOS
    sources:
      - VoxtralMemos
    dependencies:
      - package: VoxtralCore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        PRODUCT_BUNDLE_IDENTIFIER: com.meltforce.voxtralmemos
        INFOPLIST_KEY_CFBundleDisplayName: "Voxtral Memos"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Voxtral Memos needs microphone access to record voice memos."
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CODE_SIGN_ENTITLEMENTS: VoxtralMemos/VoxtralMemos.entitlements
